servicios:
  - tipo: web
    nombre: asesor-claro-ia
    entorno: python
    comandoConstruccion: pip install -r requirements.txt && python -m flask db upgrade
    comandoInicio: gunicorn --bind 0.0.0.0:$PORT app:app  # Modificado para usar $PORT
    variablesEntorno:
      - clave: FLASK_ENV
        valor: production
      - clave: SECRET_KEY
        generarValor: true
      - clave: DATABASE_URL
        desdeBaseDatos:
          nombre: chatbot-db
          propiedad: cadenaConexion
    rutaChequeoSalud: /health
    puerto: 10000