services:
  - type: web
    name: asesor-claro-ia
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download es_core_news_sm
    startCommand: gunicorn --bind 0.0.0.0:$PORT --factory app:create_app
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
